name: .NET

on: 
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore "ASP.NET/KramDeliveryFoodAPI/KramDeliveryFoodAPI.sln"
    - name: Build
      run: dotnet build "ASP.NET/KramDeliveryFoodAPI/KramDeliveryFoodAPI.sln" --no-restore
